### ISSUE TITLE
Modifications and improvements for Windows/gaming

### ISSUE THREAD

**Issue by trankillity** [marlonrichert/raise-ergo#1]
Hello friend,
Have been using your layout for about a week now and have become fairly used to it. I've spent a little time thinking about modifications to the layout which would make it work better for gaming and for Windows users. [Here's](https://drive.google.com/drive/folders/1UqhapWu2B9vAmSpOWwMHPllLD7AxiOH1?usp=sharing) a compilation of those modifications.

**BUTTON ASSIGNMENT**
- Love the position of the media volume controls in your default layer, but wanted more. Never once used F14 or F15, so reassigned those to PREV, NEXT, PLAY.
- Added the Windows key back onto Layer 1 where left CTRL sits. Fair few modifiers that use that, especially for power users.

**TRANS KEYS ON EDITING LAYERS**
I felt that having the keys transparent in the editing layers was detrimental to my learning of the new layout. I have changed all the transparent keys here to be NO KEY to prevent accidentally typing characters while on the editing layer.

**COLOUR CODING**
Made some slight modifications to your colour coding for some easier clarification and learning. It bugged me that the base layer had the same colour set as the editing layer. I'm guessing the intention there was so that you always know what fingers do what, but I found it distracting so I changed the base layer to white. Have unified the Neuron colours to show which OS layer is currently active with White being OSX, and Blue being Windows. I've also tried to unify the colours depending on their function.

**NEW LAYERS FOR DEFAULT QWERTY**
Added in some layers to switch to default QWERTY layout so that you can more easily jump to a layout that doesn't need modification of your gaming keybinds. Stuck these on the left Move To N (numpad layer). Will likely need you to test the Layer 8 as I don't actually have a Mac to test with.

**OUTSTANDING ISSUES**
- Not totally sold on the placement of the square brackets. I use them very frequently as a data scientist, and they're not the most convenient (especially closing bracket ]).
- Fairly frequent misfired activation of hold modifier on space/shift/tab thumb cluster. Not sure if this is the switch types (may need clicky types for thumb cluster specifically), or if it's the hardware delay on switching layers.

**Comment by marlonrichert** [comment]
> Here's a compilation of those modifications.

Could you please provide SVGs (through Bazecor’s developer tools) or screenshots of those, to make it easier for me to review them? :)

> Added the Windows key back onto Layer 1 where left CTRL sits. Fair few modifiers that use that, especially for power users.

Ah, the Windows key; I completely forgot about it. Thanks for pointing it out. That’s a very important one!

> I felt that having the keys transparent in the editing layers was detrimental to my learning of the new layout. I have changed all the transparent keys here to be NO KEY to prevent accidentally typing characters while on the editing layer.

Thanks, that sounds like a good idea.

> Not totally sold on the placement of the square brackets. I use them very frequently as a data scientist, and they're not the most convenient (especially closing bracket ]).

I’ve tried many different positions for the square brackets. This is the one I personally found to be best. But if you have any suggestions for their placement, I’d be happy to try them. :)

> Fairly frequent misfired activation of hold modifier on space/shift/tab thumb cluster.

I’m using the standard Cherry MX Brown switches that came with my Raise and I’m a fairly fast touch-typist, but I almost never have problems with this. If the issue persists, you should contact Dygma about it.

Though, perhaps it could also be you need a little retraining for it. While typing, if your thumb is still pressing the space/shift/tab while you press the next key, then of course the Raise will count that as both keys being pressed together. To correct for this, you will need to type more in a manner like playing the piano, where you shouldn’t press any key longer than necessary. :)

**Comment by trankillity** [comment]
Sure thing friend, I've added SVGs into the [same folder](https://drive.google.com/drive/folders/1UqhapWu2B9vAmSpOWwMHPllLD7AxiOH1?usp=sharing).

In terms of the misfires, it's less that there's misfires when typing the next character after the intended character, more that there seems to be a fairly long delay before the modifier actually kicks in. The very frequent example is when attempting to activate the left shift. Instead of getting the correct capitalised character, I often get a single quote then the character. E.g. I results in 'i.

My finger definitely isn't off the modifier key while typing that character, which makes me think it's either a delay in the firmware registering the modifier, or something to do with the switch itself. I've previously used Cherry MX Red at work, and Logitech Romer G at home, so it could just be me getting used to the Kailh Coppers. Whatever the case, it's very frustrating when you're normally a fast typist and it's generating errors.

**Comment by marlonrichert** [comment]
Oh OK, so it’s actually the _opposite_ of what I was thinking. And now that you mention, I have sometimes experienced that on my Raise when typing. You should definitely report it to Dygma; I will do so, too. There might be something they can do about it in the firmware or in Bazecor.

**Comment by trankillity** [comment]
I've just started a test to see if it's perhaps the custom keys in the thumb cluster causing it. Made the left shift button (\) a shift-when-held too. That should help discern whether it's firmware or hardware related.

**Comment by marlonrichert** [comment]
> Never once used F14 or F15, so reassigned those to PREV, NEXT, PLAY.

F14 and F15 on macOS are by default assigned to decrease/increase screen brightness. I use them quite often.

**Comment by marlonrichert** [comment]
> Have unified the Neuron colours to show which OS layer is currently active with White being OSX, and Blue being Windows.

I used Red for macOS and Purple for Windows. :)

> I've also tried to unify the colours depending on their function.

That's what I've done, too, but I guess you view the functions of the keys a bit differently than I do?

**Comment by marlonrichert** [comment]
@trankillity  I added most of your ideas in 7709f17. Thanks for your feedback!
